### PR TITLE
Praise the sun! (and other light emitting bodies)

### LINKED ISSUE #208: Solar panel stores negative energy at night
### Mod Loader

Fabric

### Version Information

c683f64

### Log or Crash Report

not a crash

### Reproduction steps

1. place solar panel (in overworld)
2. connect to an energy storage, maybe important
3. /time set night
4. power drains into the negatives

Screenshot

also minor nitpick, inconsistent use of gJ (galacticraft joules) and Gj (giga lowercase j), also saw G GJ (giga gigajoules) in the lang file
but this was probably fixed recently with the crowdin stuff

### PR DESCRIPTION
**Pull request by g307m**
Fixes #208 and moves duplicate code from solar panels to an abstract class.

### CODE REVIEW

**Comment by grantlmul** [comment]
By the way, how do I hide the old commits?

**Comment by craftablescience** [comment]
> By the way, how do I hide the old commits?

You can use GitHub Desktop to squash all these commits into a singular commit, then force-push.

Alternatively, use git interactive rebasing.

**Comment by grantlmul** [comment]
Squashing. I'll do that in the future.

**Comment by grantlmul** [comment]
oh it decided to add that to the pr, didnt work

**Comment by grantlmul** [comment]
eh, i'll just nuke the fork later

**Comment by DeltaNedas** [comment]
```
git rebase -i HEAD~16
```
then make every commit after the first `s` instead of `pick` to squash them

**Review by Jab125 — APPROVED** [review]

**Pull request closed without merging**
