### PR TITLE
chore: Updating MachineLib tank mechanics

### PR DESCRIPTION
**Pull request by supersimple33**
This pr is paired with https://github.com/TeamGalacticraft/MachineLib/pull/6, it updates the machine lib version and flips Fluids to be registered after blocks which is important for pulling names from the registries, for example not doing so causes oil and fuel to call themselves air in the Tank view of machines.

### CODE REVIEW

**Comment by supersimple33** [comment]
Blocked by https://github.com/TeamGalacticraft/MachineLib/pull/6. Need to wait for merge to give a commit hash code so I can set that hash to the machine lib version.

**Comment by supersimple33** [comment]
no longer blocked

**Review by AlphaMode — APPROVED** [review]

**Comment by supersimple33** [comment]
Should I be targeting 1.19.4 or 1.20.1

**Comment by supersimple33** [comment]
Also, #265 should fix the build check that's failing

**Comment by AlphaMode** [comment]
Ideally 1.20.1 but i can always just merge it

**Comment by supersimple33** [comment]
All fixed up, you may want to merge #265 first as it will allow for passing the build action

**Review by AlphaMode — APPROVED** [review]

**Comment by SteveKunG** [comment]
This commit break Grating and Walkways which handlers custom fluids blockstate.
https://github.com/TeamGalacticraft/Galacticraft/pull/271/commits/5fc2f98f0904f0da3eb87500e8e913daabb62ede

**Comment by supersimple33** [comment]
I'll see if I can find a workaround that keeps the original ordering but registers the names at the right time

**Pull request merged**
