### PR TITLE
Create ru_ru translation

### PR DESCRIPTION
**Pull request by DrHesperus**

### CODE REVIEW

**Comment by mMONTAGEe** [comment]
Translations are done in Crowdin for easier management,Translating and proofreading
https://crowdin.com/project/galacticraft

Russian translation already finished by me and some others, if you able to proofread it feel free to

**Comment by Seniorendi** [comment]
poor guy
he made the translations and now they don't get merged

**Comment by DrHesperus** [comment]
> Translations are done in Crowdin for easier management,Translating and proofreading https://crowdin.com/project/galacticraft
> 
> Russian translation already finished by me and some others, if you able to proofread it feel free to

Зачем ты каждое слово с большой буквой пишешь?

**Comment by ROMVoid95** [comment]
> > Translations are done in Crowdin for easier management,Translating and proofreading [crowdin.com/project/galacticraft](https://crowdin.com/project/galacticraft)
> > Russian translation already finished by me and some others, if you able to proofread it feel free to
> 
> Why are you capitalizing every word? Do not do this, a direct violation of the rules of translation of the text.

 a direct violation of the rules of translation of the text?

**Comment by Seniorendi** [comment]
I guess a violation of the russian grammar

**Pull request closed without merging**
