### PR TITLE
d

### PR DESCRIPTION
**Pull request by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET**

### CODE REVIEW

**Review by craftablescience — COMMENTED** [review]
No.

**Comment by ROMVoid95** [comment]
@JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET what exactly was the point of this?

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
to get a comment from you lol

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
also the java8 compile thing doesn't work

**Pull request closed without merging**
