### PR TITLE
feat: additional textures

### PR DESCRIPTION
**Pull request by Pomi108**

### CODE REVIEW

**Review by craftablescience — CHANGES_REQUESTED** [review]
I think most minecraft buckets have drops going down the sides, but otherwise I like all the textures here :)

**Comment by Pomik108** [comment]
actually it's only the lava bucket and the fish buckets. The general rule seems to be that if you dont want to spill it, it doesnt have drops – and you dont want to spill oil nor fuel, so i went with no drops

**Comment by craftablescience** [comment]
The powder buckets have it as well, I think it's a bit of an oversight they didn't add it to the water bucket personally

**Comment by Pomik108** [comment]
it might be the case.

**Comment by JoeZwet** [comment]
Please be sure to read our [contributing guidelines](https://github.com/TeamGalacticraft/Galacticraft/blob/main/.github/CONTRIBUTING.md), specifically the section on commit names.

**Comment by Pomik108** [comment]
Whoops my bad, didn't know these were a thing. I'll make sure all my future commits follow these conventions

**Comment by vos6434** [comment]
Our artists will remaster the textures.

**Pull request closed without merging**
