### PR TITLE
feat: Adding some recipes

### PR DESCRIPTION
**Pull request by supersimple33**
- Added a recipe for cryo bed following the legacy GC recipe
- Added recipes to go from nuggets to ingots for GC raw materials
- Moved duplicate recipes into single files to reduce space and keep code in the same place
- Added a recipe for silicon ore smelting for those with a silk touch pickaxe
- Removed recipes for basalt based ore since those ore do not exist

(Commits went burr in the last PR so I remade it)

### CODE REVIEW

**Review by AlphaMode — CHANGES_REQUESTED** [review]
Recipes should be data generated and added via https://github.com/TeamGalacticraft/Galacticraft/blob/main/src/main/java/dev/galacticraft/mod/data/GCRecipeProvider.java

**Comment by supersimple33** [comment]
@AlphaMode Addressed requested changes putting the new recipes into the `GCRecipeProvider.java`.
Also I added tags for tracking items with the same smelting output, and also added compatibility for blasting.

**Comment by supersimple33** [comment]
Also, do we want to track src/main/generated/.cache/ or should I put it in the .gitignore

**Comment by supersimple33** [comment]
I'm just going to remake this PR

**Pull request closed without merging**
