### PR TITLE
Feat: Added Fallen Meteor

### PR DESCRIPTION
**Pull request by SteveKunG**
Seperate from #124 

~My current fix concept is made `HeatLevel` into 0-4 `heat` block state. This should be better than updating block color every tick.~

~Still has bad performance when multiple fallen meteors are in one chunk.~ Fixed!

### CODE REVIEW

**Comment by DarianLStephens** [comment]
Are they still block entities?
I feel like it would be better if they were regular blocks with differently-colored models for the states that just updated heat level on weighted random tick, since it barely changes anything.
FPS will probably still struggle with so many hot meteors in a chunk because it's updating all that complex geometry so often, but once they cool down, there should be next to no additional performance impact.

**Comment by SteveKunG** [comment]
@DarianLStephens Yeah, I'm going to phase it out.

This is actually good so far.

**Comment by SteveKunG** [comment]
Testing with both FPS and TPS are fine.

**Review by AlphaMode — APPROVED** [review]

**Comment by DarianLStephens** [comment]
Eyy, it finally got merged!

**Pull request merged**
