### PR TITLE
the Chinese translation

### PR DESCRIPTION
**Pull request by Yexiaowei11**
[Chinese translation.zip](https://github.com/TeamGalacticraft/Galacticraft/files/8458885/Chinese.translation.zip)
The translation package is in the zip file, the translation may not be correct

### CODE REVIEW

**Comment by glowiak** [comment]
Great, but I think they won't merge it. The last commit was on 2nd January

**Comment by lvjiajjjlzy** [comment]
别的翻译都是修改json，你这上传了一个压缩包

**Comment by mMONTAGEe** [comment]
It is recommended to do translations in Crowdin
https://crowdin.com/project/galacticraft

**Comment by lvjiajjjlzy** [comment]
zh_cn.json

**Pull request closed without merging**
